title: Raffaele Marcello personal github web site
description: This is the personal github web site of Raffaele Marcello  
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog, empy for base url
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raffaele Marcello # add your name
author-img: rmarcello.png # add your photo
about-author: I am a Software Engineer ... and this is my personal Blog. Here you can find some articles about my experiences and my ideas about some IT topics. I hope you can find it interesting!
social-twitter: https://twitter.com/rmarcello
social-facebook: # add your Facebook handle
social-github: marcelloraffaele
social-linkedin: https://www.linkedin.com/in/raffaele-marcello-4b684514/
social-email: dev.rmarcello@gmail.com

# Disqus
discus-identifier: marcelloraffaele.github.io # add your discus identifier

# Tracker
analytics: UA-45995597-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
